# Generated by Django 2.0.5 on 2018-08-02 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_image',
            new_name='memberImage',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='member_info',
            new_name='memberInfo',
        ),
    ]
