# Generated by Django 2.0.5 on 2018-08-02 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0002_auto_20180802_0754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='memberImage',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='memberInfo',
            new_name='Info',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='member',
            new_name='Name',
        ),
    ]
