# Generated by Django 2.0.5 on 2018-08-02 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0003_auto_20180802_0755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Info',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Name',
            new_name='name',
        ),
    ]
