# Generated by Django 2.0.5 on 2018-08-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0004_auto_20180802_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
            ],
        ),
    ]
