# Generated by Django 2.0 on 2019-01-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0005_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('counter',), 'verbose_name': 'Band Member', 'verbose_name_plural': 'Band Members'},
        ),
        migrations.AddField(
            model_name='member',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
