# Generated by Django 2.0.5 on 2018-08-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(default='imageDefault', upload_to='images/'),
        ),
    ]
