# Generated by Django 2.0.5 on 2018-08-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_song_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.FileField(default='audiDefault', upload_to='audio/'),
        ),
    ]
