# Generated by Django 2.0.5 on 2018-08-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_song_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(default='audioDefault', upload_to='audio/'),
        ),
    ]
