# Generated by Django 2.0.5 on 2018-08-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePg', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
